name = "activities"
type = "javascript"
account_id = "4ed1f8e12cda519236361f09dd8956cf"
workers_dev = true
route = ""
zone_id = ""
webpack_config = "webpack.config.js"

[build]
command = "npm run build"
[build.upload]
format = "service-worker"